apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: wil42/playground:v2
        name: app
        ports:
        - containerPort: 80
