apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  namespace: dev
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: wil42/playground:v1
        name: app-container
        ports:
        - containerPort: 8888
