apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: dev
  labels:
    app: app
spec:
  ports:
  - port: 80
    targetPort: 8888
    protocole: TCP
    name: app
  
  selector:
    app: app
