apiVersion: v1
kind: Service
metadata:
  name: wil-playground
spec:
  type: NodePort
  ports:
  - name: http
    port: 8888
    protocol: TCP
    targetPort: 8888
    NodePort: 8888
  selector:
    app: app
